FROM nginx:alpine

# Copy all vanilla HTML/JS/CSS files into the nginx serve directory
COPY . /usr/share/nginx/html

# Modify default nginx config to listen on port 3000 instead of 80
# to match the docker-compose.yml mapping.
RUN sed -i 's/listen  *80;/listen 3000;/g' /etc/nginx/conf.d/default.conf
RUN sed -i 's/listen  *\[::\]:80;/listen [::]:3000;/g' /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
